spring:
  application:
    name: ${SPRING_APP_NAME:activityservice}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:8082}
