spring:
  application:
    name: ${SPRING_APP_NAME:activityservice}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

server:
  port: ${SERVER_PORT:8082}
