spring:
  application:
    name: ${SPRING_APP_NAME:user-service}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fitness_user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1092}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:8081}
